name: publish-docker-inner

on:
  workflow_dispatch:
    inputs:
      image_tag:
        required: true
        description: 'Set docker image tag. Default is "latest"'
        type: string
        default: latest
  schedule:
    - cron:  '00 14 * * 0-4'

jobs:
  publish_docker_image:
    runs-on: [self-hosted, docker-inner]
    env:
      DOCKER_TAG: "registry.h.pjlab.org.cn/ailab-llmrazor/xtuner:${{inputs.image_tag || 'latest'}}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          # This might remove tools that are actually needed, if set to "true" but frees about 6 GB
          tool-cache: false
          docker-images: false
          # All of these default to true, but feel free to set to "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: false
      - name: build docker
        run: |
          docker info
      - name: push to cluster
        run: |
          docker login registry.h.pjlab.org.cn -p ${{ secrets.CLUSTER_DOCKERHUB_TOKEN }} -u ${{ secrets.CLUSTER_DOCKERHUB_USERNAME }}
          
