name: publish-docker-inner

on:
  workflow_dispatch:
    inputs:
      image_type:
        required: true
        description: 'Set docker image type. Default is "latest", you can also set "manual" to genterate a manual tag'
        type: string
        default: latest
      torch_version:
        required: true
        description: 'Set docker torch version. Default is "2.9"'
        type: string
        default: '2.9'
  schedule:
    - cron:  '00 14 * * 0-4'

jobs:
  publish_docker_image:
    runs-on: [self-hosted, docker-inner]
    env:
      PYTORCH_VERSION: ${{ inputs.torch_version || '2.9' }}
      DOCKER_TAG: "pt${{inputs.torch_version || '2.9'}}_${{ github.GITHUB_SHA }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          # This might remove tools that are actually needed, if set to "true" but frees about 6 GB
          tool-cache: false
          docker-images: false
          # All of these default to true, but feel free to set to "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: false
      - name: build manual tag
        if: inputs.image_type != 'latest' && github.event_name != 'schedule'
        run: |
          export date_today="$(date +'%Y%m%d-%H%M%S')"
          echo ${GITHUB_SHA::7}
          export short_sha="${GITHUB_SHA::7}"
          echo $short_sha
          export DOCKER_TAG="registry.h.pjlab.org.cn/ailab-llmrazor/xtuner:pt${{ env.PYTORCH_VERSION }}_${short_sha}_${date_today"
          echo $DOCKER_TAG
      - name: build latest
        if: inputs.image_type == 'latest' || github.event_name == 'schedule'
        run: |
          export DOCKER_TAG="registry.h.pjlab.org.cn/ailab-llmrazor/xtuner:pt${{ env.PYTORCH_VERSION }}_latest"
          echo $DOCKER_TAG
      - name: push to cluster
        run: |
          docker login registry.h.pjlab.org.cn -p ${{ secrets.CLUSTER_DOCKERHUB_TOKEN }} -u ${{ secrets.CLUSTER_DOCKERHUB_USERNAME }}
          
